name: Build and Publish

on: [push, pull_request]

defaults:
  run:  
    working-directory: src
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nelonoel/branch-name@v1.0.1

    - name: Get version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with:
        path: version.json
        prop_path: 'version'
    - run: echo "version=${{steps.version.outputs.prop}}.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
      if: github.ref == 'refs/heads/master'
    - run: echo "version=${{steps.version.outputs.prop}}.${GITHUB_RUN_NUMBER}-${BRANCH_NAME}" >> $GITHUB_ENV
      if: github.ref != 'refs/heads/master'
    - run: echo Version is ${version}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version="${version}"
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    ## Publish and Tag
    - name: Publish NuGet
      run: dotnet nuget push PcapngUtils/bin/Release/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
    - name: Tag
      run: |
        git tag "v${version}"
        git push origin "v${version}"
