name: Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:  
  run:  
    working-directory: ./src
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    ## Publish
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/PcapngUtils/PcapngUtils.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: Haukcode.PcapngUtils
        # Regex pattern to extract version info in a capturing group
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: true
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
